Speed up column index retrieval
ecmwf/odc pull request #5
Opened 2021-09-16 17:19 UTC by wsmigaj

This PR makes the `TODATableIterator::updateMetaData()` function more efficient by
* performing the search for each column only once (by calling just `MetaData::columnIndex()`) rather than twice (with an extra call to `MetaData::hasColumn()`)
* avoiding repeated construction of a temporary string representing the column name with a `@` suffix
* removing an unnecessary call to `std::string::find()`.

On my system, this reduces the execution time of a query operating on a file containing 1,292,800 rows and 212 columns and producing an empty results set (and therefore effectively only decoding the file), i.e.
```
odc sql "select * where varno == -1" -i atms6K.odb -o /dev/null -f odb
```
by more than 25%: from 2.0 s to 1.4 s.

2021-09-16 17:19 UTC, FussyDuck commented
[![CLA assistant check](http://claassistant.ecmwf.int:80/pull/badge/not_signed)](http://claassistant.ecmwf.int:80/ecmwf/odc?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/odc?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/odc?pullRequest=5) it.</sub>

2021-09-22 14:27 UTC, wsmigaj commented
@simondsmart Would you mind having a look at this PR when you have time (or suggesting another reviewer)?

2021-09-22 15:40 UTC, simondsmart commented
@wsmigaj - many thanks for this. This looks like a good change, and I have only a few comments, which I will put inline.

Could I ask for a copy of the data (or a reduced set) that is exhibiting the performance improvement - it is larger than I would expect! We should (certainly) not be checking column existence/indices sufficiently frequently to impact runtime by 25%!

Thanks for your input!

2021-09-22 15:40 UTC, simondsmart commented on src/odc/core/MetaData.cc
> +bool columnNameMatches(const std::string &fullColumnName,
This is much improved. Thanks!

2021-09-22 15:46 UTC, simondsmart requested changes

2021-09-22 15:46 UTC, simondsmart commented on src/odc/core/MetaData.cc
> +	const size_t notFound = static_cast<size_t>(-1);
I would prefer not abusing signed/unsigned values here.
Either use a signed integer within the routine (and cast to size_t after the check that it is >= 0), or use a boolean 'found' for the check.

2021-09-22 15:46 UTC, simondsmart commented on src/odc/core/MetaData.cc
> +				throw eckit::UserError(std::string("Ambiguous column name: '") + name + "'");
Please create a derived exception type (see comment below). Something along the lines of:
class AmbiguousColumnException : public UserError {
    AmbiguousColumnException(const std::string& columnName) { ...}
    ....
};
This lets us do the exception wrapping that you do below more cleanly.

2021-09-22 15:46 UTC, simondsmart commented on src/odc/core/MetaData.cc
>  		throw eckit::UserError(std::string("Column '") + name + "' not found.");
Same here.

2021-09-22 15:46 UTC, simondsmart commented on src/odc/sql/TODATableIterator.cc
> +        if (eckit::StringTools::startsWith(e.what(), "Ambiguous column name:"))
This is something of a code smell.
By preference, I would write the inner exceptions such that they don't need to be wrapped.
But if the message cannot be written sufficiently generically, such that you really need to put the "SQL request" text in here, please define derived exception types, and then catch them specifically. Looking at the string contents is something of a smell, and is very much more brittle.

2021-09-23 10:37 UTC, wsmigaj commented
Thank you very much for the rapid review and your comments. I agree it is much better to use more specific exception types -- I've modified the code as you suggested.

What is the best way to share the file with you (I would prefer not to post it publicly on GitHub)? It is relatively large (107 MB).

2021-09-23 20:27 UTC, simondsmart commented
Please drop it into my dropbox received folder, using this file request: https://www.dropbox.com/request/qsvtHLikyKl6wIThaBcV

2021-09-28 10:00 UTC, wsmigaj commented
@simondsmart I've uploaded the file to your DropBox folder (you'll probably have received a notification from DropBox -- commenting here just in case you won't).

2021-10-08 09:21 UTC, wsmigaj commented
@simondsmart This is just a gentle reminder about this PR. Have you perhaps had a chance to benchmark the code using the provided ODB file? Are you happy with the way your comments have been addressed?

2021-10-15 21:42 UTC, simondsmart approved these changes

2021-10-15 21:43 UTC, merged

2021-10-15 21:44 UTC, simondsmart commented
Thanks @wsmigaj, much appreciated.
I'm happy with the PR - much improved over what was there before. I've been a bit overtaken with some recent personnel changes here, but hopefully I will get the chance to do the benchmarking soon! Either way, the code is improved :-).

2021-10-20 00:03 UTC, DJDavies2 commented
Is there any chance of getting this on a tag at some point?